"""Add role to users

Revision ID: 115f101c4a6e
Revises: ba7c0885bf8a
Create Date: 2025-12-05 23:17:38.491907

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "115f101c4a6e"
down_revision = "ba7c0885bf8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.String(length=20), nullable=True))

    # Set default role for existing users
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")

    # Make role column NOT NULL
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("role", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("role")

    # ### end Alembic commands ###
