"""create users

Revision ID: 9a735516b721
Revises: 5604f955dee1
Create Date: 2025-12-07 21:23:18.395473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a735516b721'
down_revision = '5604f955dee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
